# permissions for end users to edit lamps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: lamp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
  name: lamp-editor-role
rules:
- apiGroups:
  - lighting.mops.ridewithvia.com
  resources:
  - lamps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lighting.mops.ridewithvia.com
  resources:
  - lamps/status
  verbs:
  - get
