---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - lighting.mops.ridewithvia.com
  resources:
  - lamps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lighting.mops.ridewithvia.com
  resources:
  - lamps/finalizers
  verbs:
  - update
- apiGroups:
  - lighting.mops.ridewithvia.com
  resources:
  - lamps/status
  verbs:
  - get
  - patch
  - update
